version: "3.8"
services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-ticketmaster}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - ./data/db:/var/lib/postgresql/data

    app:
        image: ticketmaster
        build: "."
        restart: always
        depends_on:
            - db
        ports:
            - ${API_PORT:-8080}:${API_PORT:-8080}
        environment:
          PORT: ${API_PORT:-8080}
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${POSTGRES_DB:-ticketmaster}
          POSTGRES_USER: ${POSTGRES_USER:-postgres}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
